# 基础镜像
FROM  openjdk:17-oracle
# author
MAINTAINER mes

# 挂载目录
VOLUME /home/mes
# 创建目录
RUN mkdir -p /home/mes
# 指定路径
WORKDIR /home/mes
# 复制jar文件到路径
COPY ./jar/* /home/mes/
# 启动系统服务
ENTRYPOINT ["java","-jar","system.jar"]